import { Item } from '../types/index';

export const MOCK_ITEMS: Item[] = [
  {
    id: '0',
    name: 'Tuna 3 x 80 g ',
    defaultPrice: 2.89,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '1',
    name: 'Coca Cola 1,5 L',
    defaultPrice: 1.29,
    availableQuantity: 100,
    imageURL:
      'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
  },
  {
    id: '2',
    name: 'Chocolate, 270g',
    defaultPrice: 2.98,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '3',
    name: 'Solata Krhlolistna Kristalka',
    defaultPrice: 1.18,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '4',
    name: 'Sir Edamec Tuš, cca 2,5kg',
    defaultPrice: 6.79,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '5',
    name: 'Tekoči Sadni Jogurt Ego Slim&Vital Jagoda 250 g ',
    defaultPrice: 0.99,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '6',
    name: 'Krompir Tuš pakirano 2,5 kg',
    defaultPrice: 2.79,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '7',
    name: 'Kokošja Pašteta Argeta Junior 95 g ',
    defaultPrice: 1.09,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '8',
    name: 'Mleko Tuš Planinsko, 3,5%mm, 1l',
    defaultPrice: 0.89,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '9',
    name: 'Sušene Rozine Tuš 200g',
    defaultPrice: 0.99,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '10',
    name: 'Jajca Tuš M, hlevska reja, 10/1',
    defaultPrice: 2.19,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '11',
    name: 'Keksi Domačica, original, 300g',
    defaultPrice: 2.41,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '12',
    name: 'Beli Jelenov Hleb 1 kg ',
    defaultPrice: 4,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '13',
    name: 'Kava Barcaffe 200 g',
    defaultPrice: 2.75,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '14',
    name: 'Svetlo Pivo Union alk. 4,9 % vol. 6 x 0,5 L',
    defaultPrice: 6.29,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '15',
    name: 'Desert Snickers Super + 1, 1112g',
    defaultPrice: 1.07,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '16',
    name: 'Toast Tuš Classic 500 g ',
    defaultPrice: 1.15,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '17',
    name: 'Namaz ABC Sveži Kremni Sir Classic 100g',
    defaultPrice: 1.19,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '18',
    name: 'Paradižnik v Grozdih Grapolo',
    defaultPrice: 2.99,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '19',
    name: 'Kratka Posebna Poli 500 g ',
    defaultPrice: 4.99,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '20',
    name: 'Banane',
    defaultPrice: 0.35,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '21',
    name: 'Melone',
    defaultPrice: 2.65,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '22',
    name: 'Limone',
    defaultPrice: 0.25,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '23',
    name: 'Mešan Pirin Kruh z Drožmi Ana Roš & Tuš 400 g',
    defaultPrice: 2.59,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '24',
    name: 'Začinjen Svinjski Vrat BK Postrežno',
    defaultPrice: 9.29,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '25',
    name: 'Testenine Barilla Mini Polžki 500 g',
    defaultPrice: 1.29,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '26',
    name: 'Flips s Kikirikijem Smoki 150 g ',
    defaultPrice: 1.29,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '27',
    name: 'Rdeča Paprika Babura',
    defaultPrice: 1.21,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '28',
    name: 'Puding Vindija Čokolad 125 g',
    defaultPrice: 0.37,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '29',
    name: 'Papirnate brisače Bellis, 3-slojne, 90 list',
    defaultPrice: 1.99,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '30',
    name: 'Sadni Jogurt Jogobella Več Okusov 150 g ',
    defaultPrice: 0.44,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '31',
    name: 'Cvetača',
    defaultPrice: 2.29,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '32',
    name: "Čips Lay's slani, 140g",
    defaultPrice: 1.95,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '33',
    name: 'Piščančji File IK Postrežno',
    defaultPrice: 8.99,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '34',
    name: 'Jogurt Actimel Kids Jagoda Banana 6 x 100 g ',
    defaultPrice: 2.72,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '35',
    name: 'Surovo Maslo Tuš 250 g',
    defaultPrice: 2.39,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '36',
    name: 'Piščančje Prsi Slim & Fit Perutnine Ptuj 100 g ',
    defaultPrice: 1.55,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '37',
    name: 'Posebno Bela Moka Dobro 1 kg',
    defaultPrice: 1.12,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '38',
    name: 'Korenje SLO rinfuza',
    defaultPrice: 0.13,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '39',
    name: "Hrenovke Z'Dežele Postrežno",
    defaultPrice: 10.99,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '40',
    name: 'Čebula pakirano 1 kg',
    defaultPrice: 1.09,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '41',
    name: 'Kisla Smetana Tuš 180 g',
    defaultPrice: 0.53,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '42',
    name: 'Žemlja 60 g ',
    defaultPrice: 0.27,
    availableQuantity: 100,
    imageURL: '',
  },
  {
    id: '43',
    name: 'Belo Grozdje',
    defaultPrice: 4.99,
    availableQuantity: 100,
    imageURL: '',
  },
];
